server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        #sentinel的持久化
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            groudId: DEFAULT_GROUD
            data-type: json
            rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'